### ISSUE TITLE
The addToCart function triggers 3 times when you add the product to cart

### ISSUE THREAD

**Issue by funnzz** [retargeting/WooCommerce#13]
When an User adds a product to cart the addToCart function triggers 3 times with 3 different id's.
In the body of the website the addToCart code appears 3 times.
This issue appears to be only for the products with variations.

**Comment by Tynael** [comment]
If there are more HTML elements with the class of `single_add_to_cart_button`, then our script fires depending on how many similar classes there are.

**Comment by Tynael** [comment]
Issue wasn't reproduce in a long time and it's extremely isolated.

Will Not Fix.
